<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="stpapi.update returns error, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] stpapi.update returns error AFS/DDC/OLE: Function servers" />
	
	<title>stpapi.update returns error [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="index.html">Newbaanboard</a> &gt; <a href="index.html">Baan SIGs</a> &gt; <a href="index.html">AFS/DDC/OLE: Function servers</a> &gt; stpapi.update returns error</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">zakir_h</div><div class="date">14th February 2011, 07:41</div></div><div class="posttext">Hello Guys,<br />
<br />
Can some one help me out with this strange problem...IT is really urgent.... i am trying to automate the receipts in BAANERP 5.0c . I am attaching below the code which does the confirming of receipt after linking to a receipt number.<br />
<br />
Note: i am able to link the PO lines to receipt number successfully...<br />
<br />
<br />
function confirm.receipt()<br />
{<br />
	domain 	tcdate	temp.ddte,temp.ddtc,temp.prdt<br />
	string	temp.ardt(10)<br />
	string	temp.pono(4)<br />
	long	pono.temp,ardt.temp<br />
	<br />
<br />
	flag = tcyesno.no<br />
<br />
	| **********************  Confirm Receipt    *************************<br />
<br />
<br />
|        stpapi.enum.answer(&quot;whinh3520m000&quot;,&quot;whinhs312002&quot;,tcyesno.yes)<br />
         stpapi.put.field(&quot;whinh3520m000&quot;, &quot;whinh210.rcno&quot;, temp.rcno)<br />
	ret = stpapi.find(&quot;whinh3520m000&quot;, error.msg)<br />
<br />
	if ret and not isspace(temp.rcno) then<br />
				<br />
		ret = stpapi.browse.set(&quot;whinh3520m000&quot;,&quot;first.set&quot;,err.mesg)<br />
		while ret<br />
	<br />
			stpapi.mark(&quot;whinh3520m000&quot;,err.mesg)<br />
			ret = stpapi.synchronize.dialog(&quot;whinh3520m000&quot;, &quot;modify&quot;, err.mesg)<br />
<br />
			if ret then<br />
				stpapi.form.command(&quot;whinh3120s000&quot;,5,&quot;exec.user.4&quot;,err.mesg)<br />
				stpapi.get.field(&quot;whinh3120s000&quot;, &quot;whinh210.clot&quot;, temp.lot)<br />
 				ret = stpapi.update(&quot;whinh3120s000&quot;, true, error.msg)<br />
				error.code = stpapi.get.mess.code(&quot;whinh3120s000&quot;,error.msg)<br />
				<br />
								<br />
 				ret = stpapi.save(&quot;whinh3120s000&quot;, error.msg)<br />
				flag = tcyesno.yes<br />
<br />
<br />
				stpapi.end.session(&quot;whinh3120s000&quot;)<br />
			endif			<br />
<br />
			ret = stpapi.browse.set(&quot;whinh3520m000&quot;,&quot;next.set&quot;,err.mesg)<br />
|			message(str$(ret))<br />
<br />
		endwhile<br />
<br />
      		stpapi.form.command(&quot;whinh3520m000&quot;,5,&quot;exec.user.4&quot;,err.mesg)<br />
<br />
	endif <br />
	if flag = tcyesno.yes then<br />
		message(&quot;Receipt Number %s for PO %s was made and confirmed.&quot;,temp.rcno,tdafi018.orno)<br />
<br />
	endif<br />
<br />
	stpapi.end.session(&quot;whinh3822m000&quot;)<br />
	stpapi.end.session(&quot;whinh3520m000&quot;)<br />
	stpapi.end.session(&quot;whinh3120s000&quot;)		| End confirm Receipt Sessions<br />
	<br />
	err.mesg=&quot;&quot;<br />
<br />
<br />
}<br />
<br />
<br />
what happens is at the time of stpapi.update command,, it returns an error code.. .which is &quot;whinhs312002&quot; and does not update the table whinh210...<br />
<br />
Now what is strange, is that this error message doesnot come when we simulate the confirmation manually, then why is AFS throwing this error code... and how to handle this ..because.. .a similar message of &quot;tolerance&quot; we are already handling it while linking the lines to the PO..<br />
<br />
regards<br />
zakir</div></div><hr />


<div class="post"><div class="posttop"><div class="username">mark_h</div><div class="date">15th February 2011, 02:33</div></div><div class="posttext">Well I don't know anything about these sessions, so I recommend searching on them.  What I did notice is that you use the ret = stpapi.synchronize.dialog(&quot;whinh3520m000&quot;, &quot;modify&quot;, err.mesg) and then use ret = stpapi.update(&quot;whinh3120s000&quot;, true, error).  I believe when you use sync dialog the update goes against the main session and not the sub-session.</div></div><hr />



</div>
</body>
</html>