<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="bdb_error 520, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] bdb_error 520 Tools Development" />
	
	<title>bdb_error 520 [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="../index.html">Newbaanboard</a> &gt; <a href="../index.html">Baan Quick Support: Functional &amp; Technical</a> &gt; <a href="../index.html">Tools Development</a> &gt; bdb_error 520</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">garlapati</div><div class="date">21st September 2012, 15:27</div></div><div class="posttext">Hi,<br />
   Im getting bdb_erro520 in while running my custom script whil using the standard  function shell.update.occurance() used in tdpur4102.<br />
             i am using shell.update.occurance() in my custom script &amp; trying to deallocate - the inventory &amp; calling again shell.update.occurance() to  reallocate  + inventory with new date/qunatity. it is working fine when i am executing this script for records of same company. <br />
            if there are records belongs to different companies, after processing one company records &amp; commit is done when it is processing another company record at the 2nd call of shell.update.occurance() it is failing to fatal error<br />
<br />
2012-09-21[08:45:19]:E:baan100: ******* S T A R T of Error message *******<br />
2012-09-21[08:45:19]:E:baan100: Log message called from /port.6.1c.06.02/vobs/tt/lib/dbc/c_func.c: #416 keyword: domain_check<br />
2012-09-21[08:45:19]:E:baan100: Pid 28498 Uid 988 Euid 988 Gid 125 Egid 125<br />
2012-09-21[08:45:19]:E:baan100: user_type S language 2 user_name baan100 tty  locale ISO88591/NULL<br />
2012-09-21[08:45:19]:E:baan100: Errno 0 bdb_errno 0<br />
2012-09-21[08:45:19]:E:baan100: Log_mesg: Reference does not exist: tdpur051.cwar-&gt;tcmcs003.cwar [32L]<br />
2012-09-21[08:45:19]:E:baan100: ******* E N D of Error message *******<br />
2012-09-21[08:45:19]:E:baan100:<br />
2012-09-21[08:45:19]:E:baan100: ******* S T A R T of Error message *******<br />
2012-09-21[08:45:19]:E:baan100: Log message called from /port.6.1c.06.02/vobs/tt/mir/mir/bdb_fun.c: #1026 keyword: DB error<br />
2012-09-21[08:45:19]:E:baan100: Pid 28498 Uid 988 Euid 988 Gid 125 Egid 125<br />
2012-09-21[08:45:19]:E:baan100: user_type S language 2 user_name baan100 tty  locale ISO88591/NULL<br />
2012-09-21[08:45:19]:E:baan100: Errno 0 bdb_errno 520 (Error during buffered updates)<br />
2012-09-21[08:45:19]:E:baan100: Log_mesg: Error 606 (Reference does not exist) on tdpur051131 in SELECT<br />
2012-09-21[08:45:19]:E:baan100: ******* E N D of Error message *******<br />
<br />
this error is  not coming while inserting but while select on tiitm001 table in isls0005.read.standard.item() function of  tdpur4102.update.occurance(..) on 2nd call of shell.update.occurance() <br />
<br />
<br />
Im puzzled to understand where it is failing? even after i commit transactions and switch to new company, why its refering the previous company &amp; running into fatal error?<br />
<br />
any suggestion is greatly appreciated<br />
<br />
regards<br />
Sunil</div></div><hr />


<div class="post"><div class="posttop"><div class="username">BaanInOhio</div><div class="date">21st September 2012, 19:18</div></div><div class="posttext">You have to explicitly set the company before updating or inserting in the record buffer.  Something like:<br />
<br />
<br />
tdpur051._compnr = other.company    | Other company is a number.<br />
tdpur051.cwar = my.warehouse<br />
:<br />
:<br />
db.update(ttdpur051, db.retry)</div></div><hr />


<div class="post"><div class="posttop"><div class="username">benito</div><div class="date">21st September 2012, 19:35</div></div><div class="posttext">i don't have tdpur4102 in my system but i would make sure first that values in tdpur051.cwar also exists in tcmcs003.cwar.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">garlapati</div><div class="date">21st September 2012, 20:32</div></div><div class="posttext">i have done initializing it explicitly setting the company. then same issue popped up for another table tdinv150. i again explicitly set company for that but internally some where it is resetting the value to tdinv150._compnr = -1 &amp; the same issue repeating. So even if set it explicitly inside some where it is resetting it which i can't modify becuase it is standard. <br />
             seems its very peculiar issue i came across... <br />
<br />
any other inputs / fixes? :(</div></div><hr />


<div class="post"><div class="posttop"><div class="username">garlapati</div><div class="date">21st September 2012, 21:47</div></div><div class="posttext">even when i initialize them with ._compnr when the db.set.defaults() is called the ._compnr is being set to -1 resulting into fatal error. this db.set.defaults is being called in standard function &amp; we can't modify them. <br />
  can we deal with that?</div></div><hr />



</div>
</body>
</html>