<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="C4WS - ResourceException during doBdeCall, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] C4WS - ResourceException during doBdeCall Tools Administration &amp; Installation" />
	
	<title>C4WS - ResourceException during doBdeCall [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="../index.html">Newbaanboard</a> &gt; <a href="../index.html">Baan Quick Support: Functional &amp; Technical</a> &gt; <a href="../index.html">Tools Administration &amp; Installation</a> &gt; C4WS - ResourceException during doBdeCall</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">lfhaddix</div><div class="date">5th June 2018, 21:35</div></div><div class="posttext">We have just started using C4WS in our production environment.  We have had hundreds of transactions run through a certain bde but certain transactions get the following error.  The logs do not give us a hint as what can be wrong.  There are only a handful of parameters being sent so it is hard for it to be data.<br />
<br />
Does anyone have any insight on what to look for?<br />
<br />
<br />
05-Jun-2018 14:22:50.235 SEVERE [http-apr-8080-exec-9] com.sun.xml.ws.server.provider.SyncProviderInvokerTube.processRequest ResourceException during doBdeCall<br />
 javax.xml.ws.soap.SOAPFaultException: ResourceException during doBdeCall<br />
	at com.infor.erpln.soap.ProviderImpl.invoke(Unknown Source)<br />
	at com.infor.erpln.soap.ProviderImpl.invoke(Unknown Source)<br />
	at com.sun.xml.ws.api.server.InstanceResolver$1.invokeProvider(InstanceResolver.java:256)<br />
	at com.sun.xml.ws.server.InvokerTube$2.invokeProvider(InvokerTube.java:156)<br />
	at com.sun.xml.ws.server.provider.SyncProviderInvokerTube.processRequest(SyncProviderInvokerTube.java:78)<br />
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:598)<br />
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557)<br />
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542)<br />
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439)<br />
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243)<br />
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:444)<br />
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)<br />
	at com.infor.erpln.soap.servlet.ServletAdapter.handle(Unknown Source)<br />
	at com.infor.erpln.soap.servlet.WSServletDelegate.doPost(Unknown Source)<br />
	at com.infor.erpln.soap.servlet.WSServlet.doPost(Unknown Source)<br />
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)<br />
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)<br />
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)<br />
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)<br />
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br />
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)<br />
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)<br />
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)<br />
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)<br />
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)<br />
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)<br />
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)<br />
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)<br />
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)<br />
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)<br />
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)<br />
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)<br />
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2508)<br />
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2497)<br />
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br />
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br />
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br />
	at java.lang.Thread.run(Thread.java:745)</div></div><hr />


<div class="post"><div class="posttop"><div class="username">lfhaddix</div><div class="date">5th June 2018, 22:04</div></div><div class="posttext">com.infor.erpln.protocol.BaanConnectionException Unexpected close of BDEManager</div></div><hr />


<div class="post"><div class="posttop"><div class="username">rajeshell</div><div class="date">29th November 2022, 14:50</div></div><div class="posttext">This could be Because you might have received fatal error within the BDE.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">OmeLuuk</div><div class="date">7th December 2022, 11:45</div></div><div class="posttext">set the logging to Debug and rotate the logs after some 50 Mb, you will have much more insight in what is going wrong and what messages trigger that behavior.</div></div><hr />



</div>
</body>
</html>